name-template: 'natds-rn v$RESOLVED_VERSION released! 🚀'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🧩 Components'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
change-template: '- $TITLE (in PR #$NUMBER)'
template: |
  ## What’s Changed

  $CHANGES
